### ISSUE TITLE
Need leadership team

### ISSUE THREAD

**Issue by N2ITN** [Data4Democracy/are-you-fake-news#4]
If anyone wants to be a part of the project team, whether it's a lead, maintainer, or ambassador, please let me know!

**Comment by souravsingh** [comment]
@N2ITN I would be interested in joining the team.

**Comment by N2ITN** [comment]
Awesome, what is your background?
Also, are you on the D4D Slack yet?

**Comment by N2ITN** [comment]
Replaced with https://github.com/Data4Democracy/are-you-fake-news/issues/21
