### ISSUE TITLE
AWS API Gateway integration

### ISSUE THREAD

**Issue by N2ITN** [Data4Democracy/are-you-fake-news#5]
## Status
Unassigned

### Issue
I have a script to update and deploy a function on AWS Lambda (230MB). The missing part is setting up the AWS API Gateway via the CLI.

### Tasks
Use the AWS CLI to deploy an API PUT method on an existing API. The API needs to connect to a Lambda function using the "Lambda proxy integration" option.

**Comment by IlanaL1** [comment]
What aws account and credentials are you using?

**Comment by N2ITN** [comment]
The account is my own, but I can issue IAM roles to D4D people.

**Comment by N2ITN** [comment]
Fixed - thanks @IlanaL1 !

**Comment by N2ITN** [comment]
Come to think of it, this isn't quite finished yet!

**Comment by N2ITN** [comment]
Closing this, as the project is going towards Docker compose instead of AWS Lambda.
