### ISSUE TITLE
Web design

### ISSUE THREAD

**Issue by N2ITN** [Data4Democracy/are-you-fake-news#6]
## Status
Unassigned

### Issue
The frontend design looks good aesthetically but was made by someone who has no clue about web design (me).
There are probably basic flaws in know it's done.
Right now it uses Flask/Jinja, with CSS and some JS inside of the html templates.

### Tasks
* Fix background images so they scale correctly on mobile
* Centering charts to they center correctly on mobile
* Little things like cleaning up the html templates

This is open-ended if you think you can make it less buggy/more functional or improve the UI/UX in any way, feel free to message me `@Zach Estela` or just submit a PR.

**Comment by sprihajha** [comment]
Hey! I would like to volunteer for the tasks.

**Comment by N2ITN** [comment]
Will re-open this soon as a new issue following project restructure.
